<a href="https://colab.research.google.com/github/ChristianJFG/Portfolio-GitHub/blob/main/fold_change.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Plotting $p_{bound}$

In [ ]:
# Import package for numerical computation
import numpy as np

# Import package for interactive widgets
import panel as pn

# Our main plotting package (must have explicit import of submodules)
import bokeh.io
import bokeh.models
import bokeh.plotting

# Enable viewing Bokeh plots in the notebook
bokeh.io.output_notebook()

# Enable Panel widgets in the notebook
pn.extension()

#$
p_{bound} = \frac{\frac{P}{N_{N S}} e^{-\beta \Delta \varepsilon_p}}{\frac{P}{N_{N S}} e^{-\beta \Delta \varepsilon_p}+1}
$

In [ ]:
# Define array of RNAP copy numbers
p_array = np.linspace(0, 3000, 5000)

# Define the binding energy
delta_eps_p = - 10 # [=] kBT

# Define number of non-specific binding sites
Nns = 5e6

# Compute pbound
pbound = p_array / Nns * np.exp(-delta_eps_p) / \
         (p_array / Nns * np.exp(-delta_eps_p) + 1)

pbound

array([0.        , 0.00263673, 0.0052596 , ..., 0.92962996, 0.92964304,
       0.92965613])

# Plot $P$ vs $p_{bound}$

In [ ]:
# Create figure and store in variable `p`
p = bokeh.plotting.figure(
    frame_width=450,
    frame_height=300,
    x_axis_label="$$P$$",
    y_axis_label="$$p_{bound}$$",
    x_range=[np.min(p_array), np.max(p_array)],
    # y_range=[0, 1]
)

# Plot p_array vs pbound
p.line(x=p_array, y=pbound, line_width=3)

bokeh.io.show(p)

# Fold-change in gene expression

$$
\text{fold-change} =
\frac{1}{1 + \frac{R}{N_{NS}}e^{-\beta \Delta \varepsilon_R}}
$$

In [ ]:
# Define array of RNAP copy numbers
r_array = np.linspace(0, 3000, 5000)

# Define the binding energy
delta_eps_r = - 15 # [=] kBT

# Define number of non-specific binding sites
Nns = 5e6

# Compute the fold-change
fold_change = 1 / (1 + r_array / Nns * np.exp(-delta_eps_r))

fold_change

array([1.00000000e+00, 7.18204775e-01, 5.60311632e-01, ...,
       5.09781249e-04, 5.09679304e-04, 5.09577399e-04])

In [ ]:
# Create figure and store in variable `p`
p = bokeh.plotting.figure(
    frame_width=450,
    frame_height=300,
    x_axis_label="# repressors/cell",
    y_axis_label="fold-change",
    x_range=[np.min(r_array), np.max(r_array)],
    x_axis_type="log",
    y_axis_type="log",
)

# Plot p_array vs pbound
p.line(x=r_array, y=fold_change, line_width=3)

bokeh.io.show(p)

Define function to compute fold-change

In [ ]:
def fold_change(R, delta_eps_r, Nns=5E6):
  """
  Function to compute the fold-change in gene expression
  for a simple-repression architecture.

  Arguments
  ---------
  - `R`: array-like. Number of repressors per cell.
  - `delta_eps_r`: Float. Repressor binding energy.

  Optional Arguments
  ------------------
  - `Nns`: Int. Number of non-specific binding sites.

  Returns
  -------
  Array-like with the fold-change in gene expression
  """
  return 1 / (1 + (R / Nns) * np.exp(-delta_eps_r))

In [ ]:
fold_change(r_array, delta_eps_r)

array([1.00000000e+00, 7.18204775e-01, 5.60311632e-01, ...,
       5.09781249e-04, 5.09679304e-04, 5.09577399e-04])

In [ ]:
# Define a Panel slider to modify the binding energy
energy_slider = pn.widgets.EditableFloatSlider(
    name='delta_epsilon', start=-20, end=0, step=0.01, value=-10
)


fold_change(r_array, energy_slider.value)

array([1.        , 0.99736327, 0.9947404 , ..., 0.07037004, 0.07035696,
       0.07034387])

In [ ]:


# Create callback to update plot from slider value
@pn.depends(energy_slider.param.value)
def update_plot(energy):
  # Create figure and store in variable `p`
  p = bokeh.plotting.figure(
    frame_width=450,
    frame_height=300,
    x_axis_label="# repressors/cell",
    y_axis_label="fold-change",
    x_range=[np.min(r_array), np.max(r_array)],
    x_axis_type="log",
    y_axis_type="log",
  )
  # Plot p_array vs pbound
  p.line(x=r_array, y=fold_change(r_array, energy), line_width=3)
  return p

# Display slider and plot together
pn.Row(energy_slider, p)

Traceback (most recent call last):
 File "/usr/local/lib/python3.10/dist-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
 self._on_msg(msg)
 File "/usr/local/lib/python3.10/dist-packages/panel/viewable.py", line 472, in _on_msg
 doc.unhold()
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/document.py", line 776, in unhold
 self.callbacks.unhold()
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/callbacks.py", line 431, in unhold
 self.trigger_on_change(event)
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/callbacks.py", line 408, in trigger_on_change
 invoke_with_curdoc(doc, event.callback_invoker)
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
 return f()
 File "/usr/local/lib/python3.10/dist-packages/bokeh/util/callback_manager.py", line 185, in invoke
 callback(attr, old, new)
 File "/usr/local/lib/python3.10/dist-packages/panel/reactive.py", line 469, in _comm_change
 state._handle_exception(e)
 File "/usr/local/lib/python3.10/dist-packages/panel/io/state.py", line 436, in _handle_exception
 raise exception
 File "/usr/local/lib/python3.10/dist-packages/panel/reactive.py", line 467, in _comm_change
 self._schedule_change(doc, comm)
 File "/usr/local/lib/python3.10/dist-packages/panel/reactive.py", line 449, in _schedule_change
 self._change_event(doc)
 File "/usr/local/lib/python3.10/dist-packages/panel/reactive.py", line 445, in _change_event
 self._process_events(events)
 File "/usr/local/lib/python3.10/dist-packages/panel/reactive.py", line 384, in _process_events
 self.param.update(**self_events)
 File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 1902, in update
 self_._batch_call_watchers()
 File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 2063, in _batch_call_watchers
 self_._execute_watcher(watcher, events)
 File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 2025, in _execute_watcher
 watcher.fn(*args, **kwargs)
 File "/usr/local/lib/python3.10/dist-packages/panel/widgets/slider.py", line 904, in _sync_value
 self.param.update(**{event.name: event.new})
 File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 1902, in update
 self_._batch_call_watchers()
 File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 2063, in _batch_call_watchers
 self_._execute_watcher(watcher, events)
 File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 2025, in _execute_watcher
 watcher.fn(*args, **kwargs)
 File "<ipython-input-23-203ad232d5a3>", line 15, in update_plot
 p.line(x=r_array, y=fold_change(r_array, energy), line_width=3)
 File "<ipython-input-20-7945897eda10>", line 19, in fold_change
 return 1 / (1 + (R / Nns) * np.exp(-delta_eps_r))
TypeError: bad operand type for unary -: 'Event'
 


 Traceback (most recent call last):
 File "/usr/local/lib/python3.10/dist-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
 self._on_msg(msg)
 File "/usr/local/lib/python3.10/dist-packages/panel/viewable.py", line 472, in _on_msg
 doc.unhold()
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/document.py", line 776, in unhold
 self.callbacks.unhold()
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/callbacks.py", line 431, in unhold
 self.trigger_on_change(event)
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/callbacks.py", line 408, in trigger_on_change
 invoke_with_curdoc(doc, event.callback_invoker)
 File "/usr/local/lib/python3.10/dist-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
 return f()
 File "/usr/local/lib/python3.10/dist-packages/bokeh/util/callback_manager.py", line 185, in invoke
 callback(attr, old, new)
 File "/usr/local/lib/python3.10/dist-packages/panel/reactive.py", line 469, in _comm_change
 state._handle_exception(e)
 File "/usr/local/lib/python3.10/dist-packages/panel/io/state.py", line 436,

Row
    [0] EditableFloatSlider(end=0, name='delta_epsilon', start=-20, step=0.01, value=-9.59, width=300)
    [1] Bokeh(figure)

2023-09-16 00:42:17,422 ERROR: panel.reactive - Callback failed for object named "" changing property {'value': -9.86} 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/panel/reactive.py", line 384, in _process_events
    self.param.update(**self_events)
  File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/panel/widgets/slider.py", line 904, in _sync_value
    self.param.update(**{event.name: event.new})
  File "/usr/local/lib/python3.10/dist-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/usr/local/li